# Generated by Django 3.2.3 on 2021-05-15 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('password', models.TextField(max_length=1000)),
                ('photo', models.ImageField(default='abc.png', upload_to='data/')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(max_length=200)),
                ('notifications', models.IntegerField(default=0)),
                ('security', models.IntegerField(default=1)),
            ],
        ),
    ]
