# Generated by Django 3.2.3 on 2021-06-11 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_webcampictures_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.TextField(max_length=1000)),
                ('photo', models.ImageField(upload_to='data/')),
                ('webcampic', models.ImageField(upload_to='tempwebcam/')),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(max_length=200)),
                ('notifications', models.IntegerField(default=0)),
                ('security', models.IntegerField(default=1)),
            ],
        ),
    ]
