# Generated by Django 3.2.3 on 2021-06-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_temp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temp',
            name='photo',
            field=models.ImageField(upload_to='temp/'),
        ),
    ]
