# Generated by Django 3.2.3 on 2021-06-13 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_temp_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webcampictures',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
