# Generated by Django 3.2.3 on 2021-06-13 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='posts',
        ),
        migrations.AddField(
            model_name='demoposts',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
