# Generated by Django 3.2.3 on 2021-06-13 17:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20210613_2307'),
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('userid', models.IntegerField(default=0)),
                ('title', models.TextField()),
                ('image', models.ImageField(upload_to='posts_images/')),
                ('news_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
