# Generated by Django 3.2.3 on 2021-06-14 02:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_notifications'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demoposts',
            old_name='image',
            new_name='photo',
        ),
        migrations.RenameField(
            model_name='demoposts',
            old_name='webcamimage',
            new_name='webcampic',
        ),
    ]
