# Generated by Django 3.2.3 on 2021-06-14 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20210614_0818'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posts',
            old_name='image',
            new_name='photo',
        ),
    ]
