# Generated by Django 3.2.3 on 2021-06-14 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_rename_image_posts_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
