# Generated by Django 3.2.3 on 2021-06-14 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_notifications_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notifications',
            old_name='date',
            new_name='created_date',
        ),
    ]
