# Generated by Django 3.2.3 on 2021-06-18 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_rename_date_notifications_created_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='newscomments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('news_id', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
    ]
