# Generated by Django 3.2.3 on 2021-06-18 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_newscomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='newscomments',
            name='userid',
            field=models.IntegerField(default=0),
        ),
    ]
