# Generated by Django 3.2.3 on 2021-06-03 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.TextField(max_length=100, unique=True)),
                ('news_type', models.IntegerField(max_length=100)),
                ('title', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='news/')),
                ('news_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
