# Generated by Django 3.2.3 on 2021-06-03 04:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0003_auto_20210603_0943'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='news_id',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=36, unique=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
