# Generated by Django 3.2.3 on 2021-06-03 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0005_auto_20210603_0950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='news_id',
            new_name='id',
        ),
    ]
