# Generated by Django 3.2.3 on 2021-06-03 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0006_rename_news_id_news_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='News',
        ),
    ]
