# Generated by Django 3.2.3 on 2021-06-03 04:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('controllers', '0007_delete_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=36, primary_key=True, serialize=False)),
                ('news_type', models.IntegerField()),
                ('title', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='news/')),
                ('news_date', models.DateTimeField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('location', models.TextField(max_length=100)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
            ],
        ),
    ]
