# Generated by Django 3.2.3 on 2021-06-03 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controllers', '0008_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='location',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.TextField(),
        ),
    ]
